### ISSUE TITLE
Full form of Akka?

### ISSUE THREAD

**Issue by PalashBansal** [jboner/akka-training#2]
@jboner 
I am going through training of Actor model (akka.net) but not getting the answer to the full form of "akka". Many of the trainers are not answering or not able to answer.
If no fullform exist -- What's the origin/motivation to the name "akka" ?
[Just curious]

**Comment by jboner** [comment]
Now sure what 'fullform' means, but here is the answer to "Why the name Akka?": 
https://doc.akka.io/docs/akka/current/additional/faq.html#where-does-the-name-akka-come-from-
